События
htmlacademy-javascript/1389573-code-and-magick-21 pull request #4
Opened 2020-10-04 08:36 UTC by Dmitry27Zh

2020-10-05 07:51 UTC, babtshe requested changes

2020-10-05 07:51 UTC, babtshe commented on js/setup.js
> +const MAX_NAME_LENGTH = 25;
Если эти ограничения зашиты в вёрстке, их можно оттуда получить скриптом. Нет необходимости дублировать в константах.

2020-10-05 07:51 UTC, babtshe commented on js/setup.js
> +};
Стоит предусмотреть случай выпадения такого же цвета. В этом случае пользователю может показаться, что при клике ничего не происходит.

2020-10-05 07:51 UTC, babtshe commented on js/setup.js
> +  });
навешивание обработчика закрытия можно перенести в метод, где навешиваются остальные обработчики.
Кстати, когда попап уже открыт, обработчик на элементе для открытия не нужен.

2020-10-05 07:51 UTC, babtshe commented on js/setup.js
> +  if (evt.key === `Enter`) {
Названия кнопок лучше в константы перенести.

2020-10-05 17:52 UTC, Dmitry27Zh commented on js/setup.js
> -  fireballColor.value = getRandomItem(FIREBALL_COLORS);
не всегда работает функция получения неповторяющегося цвета, именно у фаербола, у других вроде как работате

2020-10-05 17:54 UTC, Dmitry27Zh commented on js/setup.js
> +  fireballColor.value = getNewColor(FIREBALL_COLORS, fireball.style.backgroundColor);
не работает функция получения неповторяющегося цвета именно на фаерболе, на остальных работает

2020-10-07 07:21 UTC, babtshe approved these changes

2020-10-07 07:21 UTC, merged